<a href="https://colab.research.google.com/github/nishant-harinkhede12/Python-Codes/blob/NLP/SMS_Spam_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
url = 'https://raw.githubusercontent.com/nishant-harinkhede12/Python-Codes/NLP/SMSSpamCollection'
import pandas as pd

messages = pd.read_csv(url, sep='\t',names=["label", "message"])

In [4]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [3]:
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [6]:
c = pd.DataFrame(corpus)
c.head()

                                                   0
0  go jurong point crazi avail bugi n great world...
1                              ok lar joke wif u oni
2  free entri wkli comp win fa cup final tkt st m...
3                u dun say earli hor u c alreadi say
4               nah think goe usf live around though

In [7]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()

In [9]:
x = pd.DataFrame(X)
x.head()

   0     1     2     3     4     5     ...  6290  6291  6292  6293  6294  6295
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 6296 columns]

In [12]:
# y=pd.get_dummies(messages['label'])
# # y=y.iloc[:,1].values
# y.head()
# OR
y=messages['label']
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

y = LE.fit_transform(y) 

# x[:,0] = labelencoder_x.fit_transform(x[ : ,0])

In [14]:
a = pd.DataFrame(y)
a.head()

   0
0  0
1  0
2  1
3  0
4  0

In [15]:
# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

[[940  15]
 [  8 152]]
0.979372197309417

Principal Component Analysis

In [18]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)

x_pca = pca.fit_transform(X)
# dfx_trans = pca.transform(dfx)
x_trans = pd.DataFrame(data=x_pca)

In [19]:
x_trans.head()

       0         1         2     ...          5569          5570          5571
0 -0.098596 -0.267517 -0.099339  ...  8.477735e-20  7.715211e-20 -4.462735e-20
1 -0.101451 -0.207684 -0.125821  ...  5.623903e-18 -2.315280e-18 -2.194885e-18
2 -0.131943  0.572935  0.660189  ...  1.417837e-18  4.801427e-18  1.149238e-18
3 -0.051441 -0.218183 -0.108637  ...  8.477735e-20  7.715211e-20 -4.462735e-20
4 -0.073306 -0.171074 -0.090547  ... -4.691616e-18 -1.425719e-18  8.946360e-19

[5 rows x 5572 columns]

to check accuracy of model post PCA

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_pca, y, test_size = 0.20, random_state = 0)

NOTE: MultinomialNB model cannot accept negative values

In [29]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [30]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

[[563 392]
 [ 33 127]]
0.6188340807174888